In [2]:
import pandas as pd

Загрузим табличку с нашими данными про длительность поездок такси! 

In [3]:
df = pd.read_csv('taxi_dataset_with_target.csv', index_col=0)

df.head()

vendor_id      pickup_datetime  passenger_count  \
id                                                           
id2875421          1  2016-03-14 17:24:55       930.399753   
id2377394          0  2016-06-12 00:43:35       930.399753   
id3858529          1  2016-01-19 11:35:24       930.399753   
id3504673          1  2016-04-06 19:32:31       930.399753   
id2181028          1  2016-03-26 13:30:55       930.399753   

           store_and_fwd_flag  trip_duration  distance_km  
id                                                         
id2875421                   0          455.0     1.500479  
id2377394                   0          663.0     1.807119  
id3858529                   0         2124.0     6.392080  
id3504673                   0          429.0     1.487155  
id2181028                   0          435.0     1.189925

Попробуем построить модель Линейной Регрессии!

В качестве Выборки используйте таргетную колонку (*trip_duration*) и все признаки, кроме времени начала заказа (*pickup_datetime*)

Для начала воспользуемся "коробочным решением". Для этого создайте переменную model, положите в нее класс **LinearRegression** из модуля **linear_model** библиотеки **sklearn**.

Далее воспользуйтесь методом **fit**, положите в него через запятую: массив **X**, состоящий из признаков объектов (можно pandas dataframe'ом, а можно numpy-массивом), и массив **Y** с таргетами.

In [4]:
from sklearn.linear_model import LinearRegression

### Your code is here
X = df.drop(['trip_duration', 'pickup_datetime'], axis=1)
Y = df[['trip_duration']]
model = LinearRegression()
model.fit(X, Y)


LinearRegression()

In [5]:
model.coef_

array([[198.46313674,   0.29631295,  56.46912165, 115.27353763]])

In [6]:
model.intercept_

array([171.65658146])

In [7]:
import numpy as np

numpy_array = X.to_numpy()

In [8]:
numpy_array

array([[  1.        , 930.39975328,   0.        ,   1.50047895],
       [  0.        , 930.39975328,   0.        ,   1.80711941],
       [  1.        , 930.39975328,   0.        ,   6.39208025],
       ...,
       [  1.        , 930.39975328,   0.        ,   7.83295239],
       [  0.        , 930.39975328,   0.        ,   1.09378613],
       [  0.        , 930.39975328,   0.        ,   1.13545341]])

In [9]:
model=LinearRegression()
model.fit(X,Y)

LinearRegression()

Чтобы посмотреть на значения полученных коэффициентов модели, следует обратиться к атрибуту **coef_** класса линейной регрессии. Для просмотра свободного веса, к атрибуту **intercept_** 

In [13]:
### Your code is here
model.coef_


array([[198.46313674,   0.29631295,  56.46912165, 115.27353763]])

In [11]:
model.intercept_

array([171.65658146])

In [1]:
### Полученные коэффициенты будут являться ответом на задание 5 в ЛМС.
### Перечислите коэффициенты через запятую и пробел, округлив до 3 знаков после точки.
### Используйте точку в качестве десятичного разделителя.

Теперь реализуйте функцию LinearRegressionByMatrix, которая будет принимать на вход 3 параметра:

Матрицу объект-признак **(X)**, вектор с ответами **(Y)**, булевый параметр **fit_intercept**, цель которого - добавить константный признак (состоящий из единичек), если True, и ничего не делать, если False.

Функция должна вернуть одномерный np.array объект с оцененными **$\beta_1, ..., \beta_n, \beta_0$**

Реализуйте решение через аналитическое решение в матрицах из лекции и практики:

$$
\beta^* = (X^T \cdot X)^{-1} \cdot X^T \cdot Y
$$

In [26]:
import numpy as np

### Your code is here
import numpy as np

def linearregressionbymatrix(X: np.array, Y: np.array, fit_intercept: bool = True):
    if fit_intercept:
        constant_column = np.ones((X.shape[0], 1))
        X = np.hstack((X, constant_column))

    first_res = np.dot(X.T, X)
    sec_res = np.linalg.inv(first_res)
    third_res = np.dot(sec_res, X.T)  # Transpose X in the third term
    the_d = np.dot(third_res, Y)
    
    return the_d


In [28]:
X_train = df.drop(['trip_duration', 'pickup_datetime'], axis=1).values
Y_train = df['trip_duration'].values

result= linearregressionbymatrix(X_train, Y_train)
result

array([198.46313674,   0.29631295,  56.46912165, 115.27353763,
       171.65658145])

In [5]:
### Полученные коэффициенты будут являться ответом на задание 6 в ЛМС.
### Перечислите коэффициенты через запятую и пробел, округлив до 3 знаков после точки.
### Используйте точку в качестве десятичного разделителя.

Получились ли коэффициенты такими же, как и в "коробочном" варианте?

Имея коэффициенты модели, можно восстановить предсказания для каждого объекта!

Сделайте это через операцию матричного произведения матрицы **X** и полученных коэффициентов (как результат работы *LinearRegressionByMatrix*)

In [30]:
### Your code is here
constant_column = np.ones((X.shape[0], 1))
X_with_intercept = np.hstack((X, constant_column))
really = np.dot(X_with_intercept, result)
really

array([ 818.7747282 ,  655.65912268, 1382.6469154 , ..., 1548.74134353,
        573.4306718 ,  578.2338068 ])